### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by chaserCN** [RxSwiftCommunity/Action#41] opened 2016-08-24 04:38 UTC
Hi.

I have accidentally googled this issue in RxSwift: https://github.com/ReactiveX/RxSwift/issues/573
and decided to check CocoaActions.

```
   class ReleaseMe {
        var name: String

        init(name: String) {
            self.name = name
        }

        deinit {
            print("deinit for \(name)")
        }
    }

    func request() -> Observable<Void> {
        let captured = ReleaseMe(name: "captured")

        return Observable.just(ReleaseMe(name: "just"))
            .map {_ in
                captured.name
            }
            .map(void)
    }

    private func bindModel() {
        loginButton.rx_action = CocoaAction() {[unowned self] in
            return self.request()
        }
    }

```

ReleaseMe objects are not freed when i tap the button. 
I managed to make it work only after i got rid of ReplaySubject and addDisposableTo in Action class, but i guess it is not an option :)

**Comment by ashfurrow** [comment] 2016-08-24 17:26
Cool, thanks for reporting the issue. I'll take a look asap.

**Comment by ashfurrow** [comment] 2016-08-24 20:36
I'm curious, if you tap the button a second time, does the first `ReleaseMe` get released?

**Comment by werediver** [comment] 2017-03-11 10:03
Memory management issues are what I always consider something serious.

@ashfurrow It's not clear from your last comment whether you've been able to reproduce the issue or it seems to be all right there?

**Comment by werediver** [comment] 2017-03-11 10:13
Is it related to the pull-request #33?

**Comment by eXhausted** [comment] 2017-04-12 16:25
any updates?

**Comment by xnxin** [comment] 2017-06-26 12:10
Is this problem fixed?

**Comment by ashfurrow** [comment] 2017-06-26 14:17
It sounds like #33 fixed this but I can't remember for sure. If someone were able to test for us, that would be a welcome contribution 🙇

**Comment by ixrevo** [comment] 2017-06-26 14:52
Action 3.1.1 
Cannot reproduce this.

**Comment by ashfurrow** [comment] 2017-06-26 14:55
Thanks for checking @ixrevo 🙇 I'm going to close this, but if anyone finds any problems please don't hesitate to let us know in a new issue.

**Closed by ashfurrow** 2017-06-26 14:55 UTC
